site_name: "ynab-memo-parser"

theme:
  name: readthedocs

plugins:
- search
- autorefs
- mkdocstrings:
    handlers:
      python:
        paths: [ynabmemoparser]
        options:
          docstring_style: sphinx
          show_root_heading: true
          show_root_full_path: true
          show_root_toc_entry: true
          show_source: false
  #        merge_init_into_class: true
#         show_signature_annotations: true
#          separate_signature: true
#         signature_crossrefs: true
          parameter_headings: false
          heading_level: 3
          line_length: 80
        enable_inventory: true

nav:
  - 'index.md'
  - 'basic_usage.md'
  - 'detailed_usage.md'
  - 'reference.md'
